### ISSUE TITLE
productsに記述

### ISSUE THREAD

**Issue by loadoff-kashiwagi-rena** [YuriTakagi/supotta-lp-spa#9]
- <main>コンポーネント作成
- 記述追加

**Comment by YuriTakagi** [comment]
- 製品一覧ページのテキスト部分を記述する
<img width="1010" alt="スクリーンショット 2024-10-08 23 11 45" src="https://github.com/user-attachments/assets/e176f9b2-10b1-4a19-94e6-d40b4d3b1057">
